### PR TITLE
Update checka11y.css

### PR DESCRIPTION
**Pull request by Neetika146**
beautified

### Did you test on all major browsers?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

## Other details

---

## T&Cs

- [ ] I confirm I have read and understand the [contributing guidelines](../CONTRIBUTING.md)
- [ ] I understand the work in this pull request will not be released straight away and will appear in a future release (if approved)
- [ ] I confirm the work in this pull request is true and valid to the best of my knowledge
- [ ] I have updated the [README](../README.md), [features.md](../features.md) and [codes.md](../codes.md) files where applicable

### CODE REVIEW

**Comment by jackdomleo7** [comment]
Clearly spam

**Comment by Neetika146** [comment]
Plz don't mark it spam 🙏🙏🥲. It would lead to disqualification of all my
hard work. I beg you to pardon me this time.

**Comment by jackdomleo7** [comment]
Hard work? You changed 1 colour of 1 CSS variable in a file that gets overwritten when you run `npm run build`. You clearly haven't researched the project, you haven't given me any good reason why that colour needs changing, you ignored the PR template, and you got your PR in just before the end of October which I'm assuming is for Hacktoberfest. No, this is a spam PR.

**Comment by Neetika146** [comment]
I am really sorry I won't do this again. Actually, I was in a pressure of
managing so many things and I am currently in my second year and my peers
are doing so much but I am trying my level best to cope up. I won't lie to
u but I did that in fomo I never meant to do anything wrong to anyone. Plz
do give me a chance I would work on myself this year and next year I
promise to contribute on your repository and u would be really happy with
me.🙏🙏🙏

**Comment by Neetika146** [comment]
Mt intentions were never wrong I just wanted to explore new things and try
to be familiar with open source. I am a complete beginners so I did k what
harm I am causing to the project. Kindly pardon me and plz don't mark it as
spam.🙏🥹🥲 May Gbu!

**Comment by Neetika146** [comment]
Didn't know*

**Comment by Neetika146** [comment]
Plz sir plz don't do this to me. I'm really really sorry for everything plz
sir I beg you to pardon me and plz give me a chance.😭😭😭😭😭

**Pull request closed without merging**
