### PR TITLE
Check order headings

### LINKED ISSUE #13: Check for correct order of heading tags
Headings should be in the correct order [See here for more information](https://www.w3.org/WAI/tutorials/page-structure/headings/). 

> Skipping heading ranks can be confusing and should be avoided where possible

For example, this is correct:

```html
<h1>This is a heading</h1>
<h2>This is a subheading</h2>
```

This is incorrect because it goes from `h1` straight to `h3` (skipping `h2`):

```html
<h1>This is a heading</h1>
<h3>This is an h3 heading</h3>
```

Not completely sure how this can be done with `CSS`. I have tried this

```css
h1+h3,
h1+h4 {
    border: var(--checka11y-error-border-width, 5px) solid var(--checka11y-error-color, red) !important;
}
```

which checks if an `h1` heading is followed by an `h3` or `h4` header. However, this doesn't take into account elements in between the headers. Any ideas welcome.

### PR DESCRIPTION
**Pull request by alvaromontoro**
Add an error message if the heading levels are not in the right order. This solution combines the methods described in #13 to resolve that issue.

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Applied the selector described in the ticket, but soon found other cases in which it was insufficient, so I had to extend it (a lot). Also, included Una Kravets solution (linked in the ticket).
Resolves #13. 

## Screenshot(s)

Screen Shot 2020-11-19 at 11 50 50 PM

## Checklist:

- [x] I have thoroughly read the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [x] I understand my pull request will be thoroughly reviewed at high detail.
- [x] I understand the work in my pull request will **only** be available in the next version release of Checka11y.css and not in the current version release.
- [x] I confirm the work in this pull request is valid according to my findings and is not something for anything personal.
- [x] I have updated the [README](../README.md) and/or [features.md](../features.md) where and if applicable (still put an `x` if you have considered this but thought there was nothing to add or modify).
- [x] I have added myself to the `contributors` section in `package.json` (still put an `x` if you have considered this but decided not to add yourself).
- [x] I have checked I have **not** committed any **accidental** files.
- [x] I have tested all the main modern browsers (I.e. Chrome, Firefox, Edge, Safari - please leave this unchecked if there were any browsers listed you could not test and list them in the [help](#help) section with details why you couldn't test that browser)
- [x] I have run the automated tests and added new ones to cover new code.
- [x] All new and existing a11y checks still work correctly (compare your local `test/index.html` to the `test/index.html` in the `master` branch).

## Help

Didn't test on IE.

### CODE REVIEW

**Comment by alvaromontoro** [comment]
@jackdomleo7 linting is failing but it is unclear what needs to be fixed. Is this normal?

**Comment by SavvasStephanides** [comment]
Thank you Alvaro. Great job on this. Sorry I didn't pick this up, it turned too complicated for me at the end. 

However, I did the same test I did for my code which is have 100 headings and see if it works as it should. The results have been interesting. The test is [here](https://codepen.io/SavvStudio/pen/eYzqvxd)

These error messages, for example, seem out of place (h6 after h5 for example):

image

**Comment by alvaromontoro** [comment]
@SavvasStephanides Wow! That test is way more thorough than what I did locally. Thanks for creating it :)

The logic in the CSS is as follows:

1. Mark as incorrect any descendant/sibling heading that skips one level (without taking into consideration things in between)
2. Remove the error if the heading follows the right structure (**starting from h1**)

In this case, h6 is a sibling of h5 that is a sibling of h4. The h6 is highlighted as an error because of step 1 (h6 is a sibling of h4 without considering the h5 in between), but as the heading structure is not complete (it starts at h4 instead of h1) the error is not removed.

h4 and h5 are not marked as errors (when they probably should) because they follow the right logic between them, so the check from h1 does not apply. One possible solution for that would be to mark every single heading as an error, then the step 2 in the logic above will remove the error if the right structure (from h1) is followed.

It may be an overkill, but it could work (it will mark h4 and h5 as errors too in this case because they are skipping h1, h2, and h3). With that in mind, I created a [quick demo forking yours](https://codepen.io/alvaromontoro/pen/04d2ddb2fbd3d253b697c81604642a53?editors=1100) and added three lines (233, 235, and 249). 

> Note: As an h1 was added at the top, it stops showing errors after a while (which is unfortunate but expected because with that structure –all headings are siblings–, it is impossible to know if the h5 is a descendant of the h6 that precedes it or the h4 a few lines above.

It seems to work better, but would need to run additional tests (later today, after work). Please, check it and let me know if you find anything.

**Comment by alvaromontoro** [comment]
There is another interesting case: because the solution combines your suggestion and Una's suggestion, the first valid  heading level will be marked as invalid if it had invalid headings before it (e.g. h2 will be marked as wrong in a structure like h1 > h3 > h2). 

If we remove Una's-based-code (the one with `:first-of-type`), that error will be removed, but I think it could be interesting to keep it as it is highlighting a different type of issue (although we could consider it is unnecessary because it was highlighted in the errors above it).

**Review by jackdomleo7 — APPROVED** [review]
Looks really good! Can't wait for feedback on this from users. 😬

**Comment by jackdomleo7** [comment]
@alvaromontoro I've been using Checka11y for a while now and I keep seeing the heading order error popup and I'm almost certain it shouldn't be. As an example webpage, https://levelupyourcareer.today 🤔

**Comment by SavvasStephanides** [comment]
@jackdomleo7 That's what I mentioned above. Getting this to work perfectly is a lot more complicated that it seems due to the limitation of the tool to only use CSS. I think a lot more work is needed to get this to work perfectly

**Comment by alvaromontoro** [comment]
Yes. My implementation was too "aggressive" and it assumed a particular structure (which is a big mistake). One possible solution would be to remove the requirement to have the previous headings first. For example, right now, if it finds an h2, it will show an error if there isn't an h1 in the ancestors (which is the case, as h1 and h2 are cousins on the linked page); The solution would be to remove that condition, it will cover fewer cases, but it won't throw false positives like that.

**Comment by jackdomleo7** [comment]
I think that sounds like a really good plan 😊 Let me create an issue and I'll get around to it when I can 🙂

**Pull request merged**
