### PR TITLE
Check for !important inline styles

### LINKED ISSUE #50: Avoid inline styles with !important
### Describe the new a11y feature or project enhancement

Users may define their own stylesheet for accessibility purposes. Inline styles can only be overridden using `!important`, and inline styles with `!important` cannot be overridden via a user stylesheet, so they should be avoided.

From [WebAIM](https://webaim.org/techniques/css/): "_To improve accessibility, end users may change browser default styles and may define custom styles that override any other styles in the "cascade". Pages must be adaptable and flexible to end user style customizations._"

### Describe the solution you'd like

Show an error/warning if inline styles are present and they have an `!important`, as users won't be able to override those styles with a custom stylesheet. The CSS rule could be like this:

```css
[style*="!important"] {
  /* error/warning */
}
```

### Link(s)

- [WebAIM: Accessible CSS](https://webaim.org/techniques/css/#intro)
- [MDN attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
- [MDN: The important exception](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)

### PR DESCRIPTION
**Pull request by alvaromontoro**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Adds a warning message if there is an inline style with `!important` in it.

It resolves #50 

## Link(s)

- [WebAIM: Accessible CSS](https://webaim.org/techniques/css/#intro)

## Screenshot(s)

Screenshot with text

## Checklist:

- [x] I have thoroughly read the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [x] I understand my pull request will be thoroughly reviewed at high detail.
- [x] I understand the work in my pull request will **only** be available in the next version release of Checka11y.css and not in the current version release.
- [x] I confirm the work in this pull request is valid according to my findings and is not something for anything personal.
- [x] I have updated the [README](../README.md) where and if applicable (still put an `x` if you have considered this but thought there was nothing to add or modify).
- [x] I have added myself to the `contributors` section in `package.json` (still put an `x` if you have considered this but decided not to add yourself).
- [x] I have checked I have **not** committed any **accidental** files.
- [x] I have tested all the main modern browsers (I.e. Chrome, Firefox, Edge, Safari - please leave this unchecked if there were any browsers listed you could not test and list them in the [help](#help) section with details why you couldn't test that browser)
- [x] All new and existing a11y checks still work correctly (compare your local `test/index.html` to the `test/index.html` in the `master` branch).

## Help

I tested on Chrome, Safari, and Firefox on Mac. May need some help testing on IE/Edge.

### CODE REVIEW

**Review by jackdomleo7 — CHANGES_REQUESTED** [review]
This looks really good, thank you! Could you look at what changes were recently made in #47 and edit this accordingly. (Sorry I understand this work was being done at the same time as this PR 😉). All that needs doing is the feature you added to the README needs adding to `features.md`.

**Comment by alvaromontoro** [comment]
@jackdomleo7 I fixed the merge conflict with my branch and made the change in features.md

**Review by jackdomleo7 — APPROVED** [review]
Awesome! Thank you!

**Comment by alvaromontoro** [comment]
Wow! that was fast :P

**Pull request merged**
