### PR TITLE
Set up Cypress + initial tests

### PR DESCRIPTION
**Pull request by alvaromontoro**
- Add Cypress dependency
- Generate automatic Cypress files
- Add initial tests for accesskey, autoplay, button, and html
- Update README with test information
- Update .gitignore to remove Cypress videos

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds Cypress as a testing tool (as a devDependency). It also adds a few common functions and tests for 4 of the tests (accesskey, autoplay, button, and html). 

Resolves: #66 

How to test these changes:

1. Install the new dependencies: `npm i`
2. Build the library: `npm run build`
3. Run the tests: 
   - To open the tests in a browser: `npm run cypress:open`
   - To run the tests from the command line: `npm run cypress:run`

## Link(s)

- [Cypress website](https://www.cypress.io/)
- [Cypress documentation](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)

## Screenshot(s)

Result of running `npm run cypress:run` (headless):

Cypress running on the command line (headless)

Result of running `npm run cypress:open`:

Cypress running on a browser

## Checklist:

- [x] I have thoroughly read the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [x] I understand my pull request will be thoroughly reviewed at high detail.
- [x] I understand the work in my pull request will **only** be available in the next version release of Checka11y.css and not in the current version release.
- [x] I confirm the work in this pull request is valid according to my findings and is not something for anything personal.
- [x] I have updated the [README](../README.md) and/or [features.md](../features.md) where and if applicable (still put an `x` if you have considered this but thought there was nothing to add or modify).
- [x] I have added myself to the `contributors` section in `package.json` (still put an `x` if you have considered this but decided not to add yourself).
- [x] I have checked I have **not** committed any **accidental** files.
- [x] I have tested all the main modern browsers (I.e. Chrome, Firefox, Edge, Safari - please leave this unchecked if there were any browsers listed you could not test and list them in the [help](#help) section with details why you couldn't test that browser)
- [x] All new and existing a11y checks still work correctly (compare your local `test/index.html` to the `test/index.html` in the `master` branch).

## Help

No a11y check changes, so didn't test those. It would be good to check how the tests are structured. 

It may be better to separate the tests in their own spec instead of all in a file. That way we could avoid merge conflicts too. 

Suggestions?

### CODE REVIEW

**Comment by jackdomleo7** [comment]
I'm new to GitHub in terms of CI/CD, can we run these on every PR? 🤔

**Comment by alvaromontoro** [comment]
@jackdomleo7 I would need to check if it's possible. I have set up jest tests on builds using Travis in other projects (for npm releases), but what you want is to run the tests on commit, right?

**Comment by jackdomleo7** [comment]
@alvaromontoro Don't worry about TypeScript, it was cheeky of me 😅 Later tonight, I'll have a thorough look through this branch and will pull it locally to see exactly how it works.

**Comment by alvaromontoro** [comment]
Sorry, I didn't get the TypeScript reference.

I was able to add `pre-git` to the repo. By adding `pre-git`, we can have the tests as part of the commit and/or push process: if the tests fail, users will **not** be able to commit or push (or both, depending on the settings). My main concern about that is that it uses an old version of `lodash` that shows vulnerabilities when installing. I'd need to check how to fix those.

**Comment by danspratling** [comment]
@alvaromontoro Husky might be an alternative. I've used it fairly recently with prettier (not cypress).

Or we could use a github action (this would probably be my preference) https://github.com/cypress-io/github-action

@jackdomleo7 I assume you've removed your comment on typescript as I can't see it but having tests in typescript is kind of pointless. We don't need to test the test code, only the real code 😂

**Comment by jackdomleo7** [comment]
I was thinking more of a pipeline step for every PR, is that something I have to do? 🤔

**Comment by alvaromontoro** [comment]
These are the options so far:

1. Leave it as it is right now. With no changes, tests will be there but devs will need to be run them manually (and they may skip it altogether).
2. Add a plugin to automatically run the tests on commit and prevent commits if tests fail (I have `pre-git` running locally, but `husky` may be a better option as suggested by @danspratling.)
3. Integrate with GitHub Actions to run the tests (I must admit I don't have any experience with GitHub Actions, but I can try to set it up.)

So... how should we move forward with this change and the PR?

**Comment by jackdomleo7** [comment]
I think your PR is fine as it is, However, could you add a checklist option in [this file](https://github.com/jackdomleo7/Checka11y.css/blob/master/.github/PULL_REQUEST_TEMPLATE.md) asking whether they've ran tests. Then at some future point, I will do something in the pipeline. 😊 Then this can be approved.

**Review by jackdomleo7 — APPROVED** [review]
Looking good to me!

**Pull request merged**
