### PR TITLE
logo/icon images added to assets

### PR DESCRIPTION
**Pull request by emmalearnscode**
Hello! I added the logo/icon images to the assets folder. I've done them in the sizes requested (plus one extra big icon with transparent background just incase) but let me know if you want them in any other sizes in the future.

Emma

### CODE REVIEW

**Comment by jackdomleo7** [comment]
Hi Emma! Thank you so much for this! Could ask something picky, could you follow the pull request template? It allows us to easily go back through PRs and allows a more consistent approach 😊 Also, feel free to add yourself to the contributors list in `package.json`.

**Comment by emmalearnscode** [comment]
No problem, where do I find the template? (Sorry, newbie here!)

**Comment by jackdomleo7** [comment]
When you created the PR, there should have been some default text in the description, that's the template. 😊

**Comment by emmalearnscode** [comment]
Oops, I did not realise that :)

**Comment by emmalearnscode** [comment]
Add logos and icon images - project enhancement




## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)


## Description
 5 files with different variations of a logo for Checka11y.css were added to the assets folder
It helps create a brand for CheckA11y.css
 Resolves: #20

## Link(s)



## Screenshot(s)


## Checklist:



- [x ] I have thoroughly read the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [x ] I understand my pull request will be thoroughly reviewed at high detail.
- [x ] I understand the work in my pull request will **only** be available in the next version release of Checka11y.css and not in the current version release.
- [ x] I confirm the work in this pull request is valid according to my findings and is not something for anything personal.
- [ x] I have updated the [README](../README.md) where and if applicable (still put an `x` if you have considered this but thought there was nothing to add or modify).
- [x ] I have added myself to the `contributors` section in `package.json` (still put an `x` if you have considered this but decided not to add yourself).
- [x ] I have checked I have **not** committed any **accidental** files.
- [ ] I have tested all the main modern browsers (I.e. Chrome, Firefox, Edge, Safari - please leave this unchecked if there were any browsers listed you could not test and list them in the [help](#help) section with details why you couldn't test that browser)
- [ x] All new and existing a11y checks still work correctly (compare your local `test/index.html` to the `test/index.html` in the `master` branch).

## Help


Files were not added to any website section but as they are png files they should work on all devices.

**Comment by jackdomleo7** [comment]
Ha don't worry, it's more for consistency and a way of easily handling Hacktoberfest. Thank you 😊

**Pull request merged**
