### PR TITLE
Improve speed of Cypress tests

### LINKED ISSUE #117: Improve speed of tests
### Describe the new a11y feature or project enhancement

The Cypress tests can take up to 2 minutes to run, which uses up minutes and storage in the GitHub workflow. The tests are extremely simple, so can we find a way to make the tests a lot quicker? I.e. Could we change to Jest?

### Describe the solution you'd like

Tests to runner quicker. Anything is an improvement.

### Link(s)

- https://github.com/jackdomleo7/Checka11y.css/actions/workflows/Tests.yml

### PR DESCRIPTION
**Pull request by tannerdolby**
## Description
Fixes #117 (WIP)

## Why is this important?
It removes unnecessary calls in memory to `.each()` for single element assertions. Most of the test cases benefit from using `.each()` as they have multiple HTML elements in `index.html`. 

Note: For these first two files that were modified, the time per test decreases "slightly" as we no longer are using `.each()` so it consumes less memory (e.g. less calls added to memory). This is still in progress but for that tests that only assert a single element this will yield small performance improvements.

### Did you test on all major browsers?
No tests were added, only slimmed down.

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
---

## T&Cs

- [x] I confirm I have read and understand the [contributing guidelines](../CONTRIBUTING.md)
- [x] I understand the work in this pull request will not be released straight away and will appear in a future release (if approved)
- [x] I confirm the work in this pull request is true and valid to the best of my knowledge
- [x] I have updated the [README](../README.md), [features.md](../features.md) and [codes.md](../codes.md) files where applicable

### CODE REVIEW

**Review by jackdomleo7 — APPROVED** [review]
Thanks for this PR @tannerdolby! Not much changed but I guess maybe there wasn't a lot to change but the things you did find were a good find and are better than nothing and something I will keep an eye out for in the future!

**Comment by tannerdolby** [comment]
You're welcome @jackdomleo7! This was only two files updated so there was quite a bit left to slim down (e.g. remove unnecessary `.each()` calls). I tried to signify this PR was a WIP but maybe I should have converted it to a draft to be safe.

Oh well, I have about 4-5 other test files in another branch that have `.each()` calls removed so I will submit those to complete this in a separate PR.

**Comment by jackdomleo7** [comment]
@tannerdolby Haha sorry, I didn't realise!

**Comment by tannerdolby** [comment]
No problem at all @jackdomleo7! 😅 

I will have it submitted within the next couple days.

**Pull request merged**
