### PR TITLE
Improve error displays

### LINKED ISSUE #4: Improve visibility on errors
As an accessibility tool, there can't be any accessibility issues caused by the notification of error messages, but in its current state there are definitely some problems I can see.

Suggestions:
- Images have a grayscale filter applied, along with a border
- All borders are actually double-borders, with a light-red inner border and a dark-red outer border to ensure they are visible regardless of the content, theme, etc.
- Text-based content has a forced background applied as well as a border
- Errors which are text alone aren't nearly noticeable enough, so we should work on defining clear alert styles (something like https://getbootstrap.com/docs/4.5/components/alerts/)
- add warnings for less critical issues which may occur

### PR DESCRIPTION
**Pull request by danspratling**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Improves the visibility and styling of errors to make them much clearer for the user to see.

## Fixes
This fixes #4 

## Notes
I would not recommend adding this into the current working branch as it adds a lot of overhead for other contributors, given the quantity of new styles added to each erroring element.

Instead, I would suggest adding a preprocessor (scss) like we discussed which can make this as simple as adding a single `@extend` method to our classes.

### CODE REVIEW

**Review by jackdomleo7 — APPROVED** [review]
I like this a lot!!! I'll convert it to SCSS soon.

Did you remove Comic Sans? 😅

**Comment by danspratling** [comment]
I did, screw comic sans (seriously though, it didn't add anything except being a distraction from the content - now it just inherits the font the user chooses).

**Comment by jackdomleo7** [comment]
No worries, Comic Sans was there on purpose 😜

- Clearly stands out so developer notices it
- Highly likeliness of being unique because no consumer is likely to use Comic Sans on their website

**Comment by danspratling** [comment]
Sure but I would argue that now the boxes stand out much more clearly the font doesn't matter any more, and readability should be at the forefront (Which it is as it's based on the users choice).

**Comment by jackdomleo7** [comment]
I'm all for that 😊

**Comment by danspratling** [comment]
Switched the assignee over to you @jackdomleo7 so you can continue with the SCSS changes.

**Pull request merged**
