### PR TITLE
Update Cypress from version 6 to the latest version 8.7.0

### LINKED ISSUE #113: Update from Cypress 6 to Cypress 8
### Describe the new a11y feature or project enhancement

We'd like to update Checka11y.css to use Cypress 8 rather than Cypress 6 so we can remain up to date with Cypress and make use of new features if needed

### Describe the solution you'd like

Upgrade to Cypress 8

### Link(s)

N/A

### PR DESCRIPTION
**Pull request by tannerdolby**
## Description
Fixes #113

In Cypress 8:
- All browsers run headless by default so the `--headless` flag can be removed from any `cypress run` usage
- The [default screen size](https://docs.cypress.io/guides/references/migration-guide#Default-screen-size-during-headless) when running a headless browser reverted back to 1280x720 pixels

## Why is this important?
This is important in order to utilize the newest features in v8.

## Covered test cases
No tests were added or modified.

### Did you test on all major browsers?

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari

## T&Cs

- [x] I confirm I have read and understand the [contributing guidelines](../CONTRIBUTING.md)
- [x] I understand the work in this pull request will not be released straight away and will appear in a future release (if approved)
- [x] I confirm the work in this pull request is true and valid to the best of my knowledge
- [x] I have updated the [README](../README.md), [features.md](../features.md) and [codes.md](../codes.md) files where applicable

### CODE REVIEW

**Comment by tannerdolby** [comment]
The Pipleline / tests is failing and suggests I include the package-lock.json file (after running a fresh npm install), this will be a pretty large diff but I'm happy to do it if need be.

**Comment by jackdomleo7** [comment]
Thanks @tannerdolby, yeah it'd be really good to include the `package-lock.json` (you'll just need to ensure you are using npm@7 or npm@8 so the file is generated using lockfile v2).

What really interests me about this PR is that you've literally only updated the dependency version and edited the script. Here's me thinking this was gonna need some major refactoring 😅

**Comment by tannerdolby** [comment]
You're welcome @jackdomleo7, ahh yes that was the issue. I hadn't updated `npm` in awhile so I will do that and then generate the lock file with `npm install` (ensuring its npm@7 or higher) and commit it.

Yeah, it was interesting that there wasn't really anything other than the `--headless` flag that was needing to be changed. I went through the [migration guide]() provided by Cypress (checking v7 and v8 migrations) and checked the project, these couple changes were all I could find. Maybe a deeper dive into the [8.7.0 changelog](https://docs.cypress.io/guides/references/changelog) would reveal more things potentially needing to be changed but I think this oddly enough completed the migration from 6 to 8 😅

**Review by jackdomleo7 — APPROVED** [review]
Nice one, thank you

**Comment by jackdomleo7** [comment]
@tannerdolby I'm happy to merge this PR, but there seems to be an issue with your commits not being signed 🤔 
image

**Comment by tannerdolby** [comment]
@jackdomleo7 Yeah, my bad. I forgot to sign commits in this PR, I'm not entirely sure how to go back and sign them so I can just start a new PR with the same changes and ensure the use the `-S` flag and sign my commits, I usually do just forgot we needed to adhere to that in this repo.

**Pull request closed without merging**
